### ISSUE TITLE
As an Inman agent I want to be able to add a coupon on an extension on the hub

### ISSUE THREAD

**Issue by marcelaph** [marcelaph/Hub-Optimization#10]

**Comment by corellanaph** [comment]
Coupon doesn’t work, the discount is not applied.  https://youtu.be/szNe9apBCO4

**Comment by corellanaph** [comment]
Igor's answer: This is a hub only user. The coupons work only for stripe users. The coupons are stripe coupons, and the actual amount paid for the hub only users are not stored in hub, since the users pay via check. There was talk on enabling an input field for entering an actual amount here but to this day it is not implemented.
